### PR TITLE
update addons in module argument spec

### PR DESCRIPTION
**Pull request by TheRealHaoLiu**
closes https://github.com/open-cluster-management/ocmplus.cm/issues/26

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
tested with args.json that does not contain addon section and validated that all the optional addons are defaulted to False

**Comment by TheRealHaoLiu** [comment]
according to https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec default and required should not be use at the same time. default implied not required

**Review by hanqiuzh — APPROVED** [review]

**Comment by taragu** [comment]
I thought the policy collection was the only addon that has to be turned on?

**Review by taragu — APPROVED** [review]

**Pull request merged**
