### PR TITLE
Add sanity test ignore file and fix sanity test errors

### PR DESCRIPTION
**Pull request by taragu**
For #22 and #23
Still some more TODOs

/cc @TheRealHaoLiu @hanqiuzh @CrystalChun

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
```
/Volumes/case-sensitive-volume/projects/src/github.com/TheRealHaoLiu/ocmplus.cm/.venv/bin/python3.9: No module named pycodestyle
```

`pycodestyle` required for sanity test but not in the `test-requirements.txt`

**Comment by taragu** [comment]
(PR is updated)

**Review by TheRealHaoLiu — APPROVED** [review]
tested import_eks and also tested `ansible-test sanity`
/lgtm

**Pull request merged**
